on:
  push:
    branches-ignore:
      # ignore tmp branches used by bors
      - 'staging.tmp*'
      - 'trying.tmp*'
      - 'staging*.tmp'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

name: ci

jobs:
  build:
    name: Build
    runs-on: mathport
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.3.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
          ./elan-init -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v2

      - name: build mathport
        run: make build

      - name: prepare sources and predata
        run: make predata

      - name: run mathport
        run: make port-lean port-mathbin

      - name: prepare tarballs for nightly
        run: make tarballs

      - name: set now
        run: echo "::set-env name=NOW::$(date -u +%F)"

      - name: release nightly
        uses: softprops/action-gh-release@v1
        # if: github.event_name == 'schedule'
        with:
          prerelease: true
          tag_name: nightly-${{ env.NOW }}
          files: |
            lean3-binport.tar.gz
            lean3-synport.tar.gz
            mathlib3-binport.tar.gz
            mathlib3-synport.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_NIGHTLY_TOKEN }}
